# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yqctl < Formula
  desc "CLI for the YoorQuezt MEV gateway — submit bundles, protect transactions, stream events"
  homepage "https://github.com/yoorquezt-labs/yqctl"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoorquezt-labs/yqctl/releases/download/v0.1.1/yqctl_darwin_amd64.tar.gz"
      sha256 "e3f1f4d656e15fc7b7d5323de50a923074929d974815117975622361dd15cd8b"

      define_method(:install) do
        bin.install "yqctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoorquezt-labs/yqctl/releases/download/v0.1.1/yqctl_darwin_arm64.tar.gz"
      sha256 "1e35e0ed3f7c25e9a7016cc2af6effa4ae8700b7c76001e6ea0663f05e6c6f44"

      define_method(:install) do
        bin.install "yqctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yqctl/releases/download/v0.1.1/yqctl_linux_amd64.tar.gz"
      sha256 "6e30146e7c2cea9f09f18148e2de2cbadaf3239b508ac9dffe31942470f522e0"
      define_method(:install) do
        bin.install "yqctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yqctl/releases/download/v0.1.1/yqctl_linux_arm64.tar.gz"
      sha256 "168d32ba97f88cb7ea1caa4e14b9e5366cfbd3499f3fbe1bfa992c01c5a9b5f8"
      define_method(:install) do
        bin.install "yqctl"
      end
    end
  end

  test do
    system "#{bin}/yqctl", "--help"
  end
end
