# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yqmev < Formula
  desc "MEV terminal dashboard — monitor, analyze, and interact with YoorQuezt MEV infrastructure"
  homepage "https://github.com/yoorquezt-labs/yqmev"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoorquezt-labs/yqmev/releases/download/v0.1.0/yqmev_darwin_amd64.tar.gz"
      sha256 "56f100d5a383d26832526a18cd151599d0431259c12d466fd03384d6c2e32bf9"

      define_method(:install) do
        bin.install "yqmev"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoorquezt-labs/yqmev/releases/download/v0.1.0/yqmev_darwin_arm64.tar.gz"
      sha256 "e386c062559ca13a56c66d3525210f684cde0633551599509fd4012d8dbd598d"

      define_method(:install) do
        bin.install "yqmev"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yqmev/releases/download/v0.1.0/yqmev_linux_amd64.tar.gz"
      sha256 "f1d594c88d99190444c65f39c12a641fa813fe0644976c5f2664ebd6be5f1168"
      define_method(:install) do
        bin.install "yqmev"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yqmev/releases/download/v0.1.0/yqmev_linux_arm64.tar.gz"
      sha256 "ad632132c17f68a266db5ce2fcab0969fe3a44226dc4f435f87e142bcb455176"
      define_method(:install) do
        bin.install "yqmev"
      end
    end
  end

  test do
    system "#{bin}/yqmev", "--help"
  end
end
