# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yqmesh < Formula
  desc "YoorQuezt Mesh P2P relay node"
  homepage "https://github.com/yoorquezt-labs/yoorquezt-mesh"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yoorquezt-labs/yoorquezt-mesh/releases/download/v0.1.0/yqmesh_0.1.0_darwin_amd64.tar.gz"
      sha256 "3bf442c5e6f9da492a643b94c5ba603a95b6bf68ba2a2d32fa8e4b1b0d68b11a"

      define_method(:install) do
        bin.install "yqmesh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yoorquezt-labs/yoorquezt-mesh/releases/download/v0.1.0/yqmesh_0.1.0_darwin_arm64.tar.gz"
      sha256 "e97916d833a280e36343bfef347fe31a4e84fef00f5ebe9048bb6f5c3a030072"

      define_method(:install) do
        bin.install "yqmesh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yoorquezt-mesh/releases/download/v0.1.0/yqmesh_0.1.0_linux_amd64.tar.gz"
      sha256 "3a7ef3b6ce8539d4e8e1a83a3ea71437845dfb9940694a2a5afef7eede65891f"
      define_method(:install) do
        bin.install "yqmesh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yoorquezt-labs/yoorquezt-mesh/releases/download/v0.1.0/yqmesh_0.1.0_linux_arm64.tar.gz"
      sha256 "487874e622b604c477f69545dab8603f70bf05122e22b949444c4152ee8e0324"
      define_method(:install) do
        bin.install "yqmesh"
      end
    end
  end

  test do
    system "#{bin}/yqmesh", "version"
  end
end
